### ISSUE TITLE
MGN replication agent requires additional dependencies on Amazon Linux 2

### ISSUE THREAD

**Issue by jlosito** [awsdocs/aws-server-migration-service-user-guide#5]
I know that this page is for SMS and not MGN, but it looks like the MGN documentation hasn't moved to GitHub. Therefore, I thought this issue would be helpful for anyone that might stumble upon it if they came across the same issue. If MGN moves their documentation to GitHub, then this issue can always be moved under that repository.

When trying to install the MGN replication agent on Amazon Linux 2 and run its initial setup which is stated on this [page](https://docs.aws.amazon.com/mgn/latest/ug/linux-agent.html), one will get the following error.

```
$ sudo python3 aws-replication-installer-init.py
The installation of the AWS Replication Agent has started.
AWS Region Name: us-east-1
[35559] Error loading Python lib '/tmp/_MEIJptyIS/libpython3.8.so.1.0': dlopen: libcrypt.so.1: cannot open shared object file: No such file or directory
```

I believe this is because the python installer no longer bundles libcrypt anymore.

In order to resolve this error, users will have to install the `libxcrypt-compat` package.

```
$ sudo yum install -y libxcrypt-compat
```

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
